version: '3.7'

services:
  web:
    build:
      dockerfile: web.Dockerfile
      context: .
    volumes:
      - "./configs:/cert"
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 8080:443
    depends_on:
      - ion

  ion:
    build:
      dockerfile: Dockerfile
      context: .
    command: "-c /configs/ion.toml"
    volumes:
      - "./docker/ion.toml:/configs/ion.toml"
      - "./configs/cert.pem:/configs/cert.pem"
      - "./configs/key.pem:/configs/key.pem"
    ports:
      - 6666:6666 # rtp
      - 8443:8443 # websocket
    restart: on-failure
    depends_on:
      - rabbitmq
      - etcd

  islb:
    build:
      dockerfile: islb.Dockerfile
      context: .
    command: "-c /configs/islb.toml"
    volumes:
      - "./docker/islb.toml:/configs/islb.toml"
    restart: on-failure
    depends_on:
      - rabbitmq
      - etcd
      - redis

  rabbitmq:
    image: rabbitmq:3.8.2-management
    expose:
      - 5672
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      timeout: 5s
      retries: 1

  etcd:
    image: gcr.io/etcd-development/etcd:v3.3.18

  redis:
    image: redis:5.0.7