[global]
# pprof = ":6060"

# internet ip
advertiseip = "127.0.0.1"

[webrtc]
# if ion behind nat, uncomment this
# ices = ["stun:stun.l.google.com:19302"]
# ices = ["stun:stun.stunprotocol.org:3478"]

[rtp]
# listen ip
port = 6666

[log]
level = "info"

[etcd]
# ["ip:port", "ip:port"]
servers = ["127.0.0.1:2379"]

[signal]
#listen ip port
host = "0.0.0.0"
port = "8443"
cert= "conf/cert.pem"
key= "conf/key.pem"



