[global]
# pprof = ":6060"

[log]
level = "info"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["127.0.0.1:2379"]

[amqp]
url = "amqp://guest:guest@localhost:5672/"

[redis]
addrs = [":6379"]
password = ""
db = 0
